[project]
name = "src"
version = "0.1.0"
description = "Tabeeby Agent - Autonomous AI Medical Assistant"
readme = "README.md"
authors = [
    { name = "amr10w", email = "amrw5189@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "google-genai>=2.19.0",
    "ipykernel>=7.3.0",
    "ollama>=0.6.2",
    "openai>=3.3.1",
    "pandas>=2.2.0",
    "pathlib>=1.0.1",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "python-telegram-bot>=22.8",
    "qdrant-client>=1.19.0",
    "redis>=8.1.0",
    "tavily-python>=0.7.27",
    "tqdm>=4.66.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
src = "src:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
